I only got at one place.
I deleted the **original_content** definition in **handler_message** block due to which I got an error.
I lazily copy pasted the comments in the return block of **def usage** in **links.py** due to which I was getting comments of **followup.py**.